eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ApiFindOne
  main:
    allow-bean-definition-overriding: true
server:
  port: 9805
feign:
  httpclient:
    enabled: true



