eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: GoodsConsumer
  main:
    allow-bean-definition-overriding: true
  mvc:
    async:
      request-timeout: 20000
server:
  port: 9601
feign:
  httpclient:
    enabled: true




